### ISSUE TITLE
Hello, can you tell me how the model file "stage2.pth" in your "rl-collision-avoidance" code was trained? Why does the model I trained based on the code you gave use "circle_test.py" to test poorly (because it can't be turned in advance, it causes a collision)?

### ISSUE THREAD

**Issue by zhinengshidai** [Acmece/rl-collision-avoidance#9]

**Comment by Acmece** [comment]
Hi, you do not need model the file "stage2.pth", it is the output of the script "ppo_stage2.py".

The trained models are already provided. The test of circle_test.py should be fine. Please make sure you are running the scripts under the root directory of the repo and are using the configuration in the  "worlds" directory instead of it in the "word" directory of "stage_ros-add_pose_and_crush"

**Comment by zhinengshidai** [comment]
Thanks a lot! by the way, Can you tell me how to train a better model without relying on any model?
